
on:
  push:
    branches:
      - main

jobs:
  setup_go:
    name: Setup Go
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'cmd/cmd1'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Test
        run: go test ./...